### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-julia#2]
<img width="1136" alt="Schermafbeelding 2020-07-19 om 13 08 13" src="https://user-images.githubusercontent.com/2431823/87873329-f89a7f80-c9c0-11ea-9f2d-4385676bd7d6.png">

I'm seeing a bunch of missing references, but I don't know how that could be fixed. This is the source code of https://github.com/julia-vscode/LanguageServer.jl running with the language server itself, so I would expect to see no errors/warnings.

**Comment by rwols** [comment]
It might be related to https://github.com/julia-vscode/LanguageServer.jl/issues/804

**Comment by jwortmann** [comment]
The linter should see all installed packages from the current environment now, and there shouldn't be a warning anymore.
