### ISSUE TITLE
Rename to LSP-julia?

### ISSUE THREAD

**Issue by jwortmann** [sublimelsp/LSP-julia#3]
My version of this package is called LSP-julia with lowercase "j", because based on the other LSP-* packages this seems to be the convention. I could make a pull request to replace all the files here, but I think it would be easier to delete this repo and transfer ownership of my repo to sublimelsp directly, and I guess existing clones get redirected then automatically.

The other two issues here are fixed in my version.

**Comment by rwols** [comment]
Renamed this to LSP-julia.

You can change your git remote to point to this location and force-push the master branch. I believe there are a few difficulties when transferring repos with outside collaborators.

**Comment by rwols** [comment]
I prefer naming the package with correct casing, e.g. `LSP-PowerShellEditorSerivces`, but it's up to you.
